// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMNPTutVPm5AJfJp-ZmO9VdKkOj2KTlYE',
    appId: '1:536231116:web:4ffda6dd7a8ce46714d669',
    messagingSenderId: '536231116',
    projectId: 'jgoapplication',
    authDomain: 'jgoapplication.firebaseapp.com',
    databaseURL: 'https://jgoapplication-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jgoapplication.appspot.com',
    measurementId: 'G-ST9X07CF7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbbvAgvc5_yiOiFz_bQZa29ElH32UW9E4',
    appId: '1:536231116:android:199539d12a92accd14d669',
    messagingSenderId: '536231116',
    projectId: 'jgoapplication',
    databaseURL: 'https://jgoapplication-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jgoapplication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_KE83KZa6uRRJHEbd_emct2IjOtHk-K8',
    appId: '1:536231116:ios:e3d45b522575041414d669',
    messagingSenderId: '536231116',
    projectId: 'jgoapplication',
    databaseURL: 'https://jgoapplication-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jgoapplication.appspot.com',
    androidClientId: '536231116-037phmoh364cr094gpr5gnp0s6s8bvrl.apps.googleusercontent.com',
    iosClientId: '536231116-tcofsp9vhj04k7ls4kjet0r0o9s341rq.apps.googleusercontent.com',
    iosBundleId: 'com.jgo.jgoapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_KE83KZa6uRRJHEbd_emct2IjOtHk-K8',
    appId: '1:536231116:ios:e3d45b522575041414d669',
    messagingSenderId: '536231116',
    projectId: 'jgoapplication',
    databaseURL: 'https://jgoapplication-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jgoapplication.appspot.com',
    androidClientId: '536231116-037phmoh364cr094gpr5gnp0s6s8bvrl.apps.googleusercontent.com',
    iosClientId: '536231116-tcofsp9vhj04k7ls4kjet0r0o9s341rq.apps.googleusercontent.com',
    iosBundleId: 'com.jgo.jgoapplication',
  );
}
